{ pkgs ? import <nixpkgs> {}, lib ? pkgs.lib }:

let
  systemToPlatform = {
    "x86_64-linux" = "glnxa64";
    "aarch64-linux" = "glnxa64";
    "x86_64-darwin" = "maci64";
    "aarch64-darwin" = "maca64";
    "x86_64-windows" = "win64";
    "i686-windows" = "win64";
  };

  # Helper to parse a JSON file
  loadJson = file: builtins.fromJSON (builtins.readFile file);

  # Separator characters replaced during case normalization. Product aliases are
  # generated by nix/scripts/resolve.py, which keeps its own copy of this list;
  # these helpers remain for callers that normalize other strings (the builder
  # derives derivation names from component filenames this way).
  sepChars = [ " " "-" "_" "." "/" ":" "(" ")" "[" "]" "," "+" "@" "#" "$" "%" "^" "&" "*" ];
  replaceSep = sep:
    let seps = builtins.genList (_: sep) (builtins.length sepChars);
    in str: builtins.replaceStrings sepChars seps (lib.toLower str);

  # Normalize string to lowercase snake_case or kebab-case
  toSnakeCase = replaceSep "_";
  toKebabCase = replaceSep "-";

  # Deduplicate component records by filename
  dedupComponents = comps:
    builtins.attrValues (
      builtins.listToAttrs (
        map (c: { name = c.fn; value = c; })
          (builtins.filter (c: c.fn != "") comps)
      )
    );

  # Load all releases and their availableUpdates from versions.json
  loadVersions = dataDir:
    builtins.filter (v: (v.availableUpdates or []) != [])
      (loadJson (dataDir + "/versions.json"));

  # Load the signing key from data/key.txt
  loadKey = dataDir:
    lib.strings.trim (builtins.readFile (dataDir + "/key.txt"));

  # Path of the database holding one update's product and component metadata.
  #
  # Databases are per update, not per release: MathWorks repacks every component
  # for every update, so the same componentFileName served under
  # .../Release/0/... and .../Release/1/... has different bytes. Keeping them
  # separate also means resolving one update never reads another's data.
  dbPath = dataDir: release: update: dataDir + "/${release}.${update}.sqlite";

  # Resolve one update's product tree for one platform, via import from
  # derivation.
  #
  # The join lives in Python rather than here so that Nix reads a single JSON
  # file per (release, update, platform) instead of walking hundreds of
  # per-product files. This is IFD: forcing the result blocks evaluation until
  # the derivation is built, so it must stay inside the per-update thunk in
  # default.nix, or evaluating any package would resolve every release.
  resolveUpdate = { dataDir, release, update, platform }:
    let
      db = dbPath dataDir release update;
      resolved = pkgs.runCommand "matlab-data-${release}.${update}-${platform}.json" {
        nativeBuildInputs = [ pkgs.python3 ];
        # Cheap to produce and specific to this checkout; never worth a
        # substituter round-trip.
        preferLocalBuild = true;
        allowSubstitutes = false;
      } ''
        python3 ${./scripts/resolve.py} ${db} ${platform} > $out
      '';
    in
    if builtins.pathExists db then
      loadJson resolved
    else
      throw "nix-matlab: no component database at ${toString db}; run scripts/main.py to generate it";

  # Load products and components for a specific release and update
  loadReleaseData = { dataDir ? ../data, system ? "x86_64-linux", release, update }:
    let
      platform = systemToPlatform.${system} or "glnxa64";
      resolved = resolveUpdate { inherit dataDir release update platform; };

      # The database stores component filenames, not URLs: every URL under an
      # update shares one prefix, so it is emitted once and rejoined here.
      withUrl = comp: comp // { url = resolved.urlPrefix + comp.fn; };

      productList = map (p: p // { components = map withUrl p.components; })
        resolved.productList;

      # Build the products map where each alias points to the product
      # Also provide canonical list of unique products
      uniqueProductsMap = builtins.listToAttrs (
        map (prod: { name = prod.name; value = prod; }) productList
      );

      aliasedProductsMap = builtins.listToAttrs (
        builtins.concatMap (prod:
          map (alias: { name = alias; value = prod; }) prod.aliases
        ) productList
      );

    in {
      inherit release update platform productList;
      products = aliasedProductsMap;
      uniqueProducts = uniqueProductsMap;
    };

in {
  inherit systemToPlatform toSnakeCase toKebabCase loadJson dedupComponents
    loadVersions loadKey dbPath resolveUpdate loadReleaseData;
}
