name: Generate Matlab Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Compile hook.c
        run: gcc -shared -fPIC -o hook.so hook.c
      - name: Download mpm
        run: |
            wget https://www.mathworks.com/mpm/glnxa64/mpm
            chmod +x mpm
      - name: Install dependencies
        run: pip install requests
      - name: Run main.py
        run: python scripts/main.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update Matlab Data"
          git push