name: Generate DWS ZIP

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Compile hook.c
        run: gcc -shared -fPIC -o hook.so hook.c
      - name: Download mpm
        run: |
            wget https://www.mathworks.com/mpm/glnxa64/mpm
            chmod +x mpm
      - name: Run generate.py
        run: python generate.py
      - name: Strip BadRequest lines
        run: sed -i '/BadRequest/d' versions.jsonl
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "Update Matlab Data"